Models/Company.cs
using System;
using System.Drawing;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseManager.Models
{
    public class Company
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        //public bool HasLogo { get; set; }
    
        public string DisplayName()
        {
            return "Name: " + Name;
        }

        public string DisplayWebsite()
        {
            return "Website: " + Website;
        }

        public string DisplayEmail()
        {
            return "Email: " + Email;
        }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseManager.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public virtual Company PlaceOfWork { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

        public string DisplayName()
        {
            return "Name: " + FirstName + " " + LastName;
        }

        public string DisplayCompany()
        {
            return "Company: " + PlaceOfWork.Name;
        }

        public string DisplayNumber()
        {
            return "Number: " + PhoneNumber;
        }

        public string DisplayEmail()
        {
            return "Email: " + Email;
        }
    }
}

Controllers/DatabaseManagerController.cs
using DatabaseManager;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CSharpReflection3.Controllers
{
    public class DatabaseManagerController : Controller
    {
        private readonly ILogger<DatabaseManagerController> _logger;
        public static Employee employeeToDelete = new Employee();
        public static Company companyToDelete = new Company();
        public DatabaseManagerController(ILogger<DatabaseManagerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Database Manager";
            return View();
        }

        public IActionResult Company()
        {
            ViewBag.Title = "Company Management";
            return View();
        }

        public IActionResult CompanyAdd()
        {
            ViewBag.Title = "Add Company";
            return View();
        }

        [ActionName("CompanyAdd"), HttpPost]
        public IActionResult CompanyAdd(string name, string email, string website, object? logo)
        {
            Company companyToAdd = new Company()
            {
                Name = ModelState["Name"].AttemptedValue,
                Website = ModelState["Website"].AttemptedValue,
                Email = ModelState["Email"].AttemptedValue
            };

            DatabaseManagement.AddCompanyToDb(companyToAdd);
            return RedirectToAction("Company");
        }

        public IActionResult CompanySearch()
        {
            ViewBag.Title = "Search for Company";
            return View();
        }

        [ActionName("CompanySearch"), HttpPost]
        public IActionResult CompanySearch(string name, string website, string email) //, object? logo logo search broken 
        {
            DatabaseManagement.GetRefinedCompanySearchResults(
                ModelState["Name"].AttemptedValue,
                ModelState["Website"].AttemptedValue,
                ModelState["Email"].AttemptedValue
                );

            return RedirectToAction("CompanySearchResults");
        }

        public IActionResult CompanySearchResults()
        {
            ViewBag.Title = "Company Search Results";
            return View();
        }

        [ActionName("CompanySearchResults"), HttpPost]
        public IActionResult CompanySearchResults(Company company)
        {
            ViewBag.CompanyToView = company;
            return RedirectToAction("CompanyUpdate");
        }

        public IActionResult CompanyUpdate()
        {
            ViewBag.Title = "Update Company";
            return View();
        }

        public IActionResult CompanyView()
        {
            ViewBag.Title = "View Company";
            return View();
        }

        public IActionResult CompanyDelete()
        {
            ViewBag.Title = "Delete Company";
            return View();
        }

        public ActionResult DeleteCompany(string deleteCompany)
        {
            using (Context context = new Context())
            {
                DatabaseManagement.SelectedCompany = context.Companies.Find(Int32.Parse(deleteCompany));
            }
            return RedirectToAction("CompanyDelete");

        }

        public ActionResult ConfirmDeleteCompany()
        {
            using (Context context = new Context())
            {
                DatabaseManagement.DeleteCompanyFromDb(DatabaseManagement.SelectedCompany);
            }
            return RedirectToAction("Company");
        }
        public ActionResult SelectCompany(string updateCompany)
        {
            using (Context context = new Context())
            {
                foreach (Company company in context.Companies)
                {
                    if (company.Id == Int32.Parse(updateCompany))
                    {
                        DatabaseManagement.SelectedCompany = company;
                        break;
                    }
                }
            }
            return RedirectToAction("CompanyView");
        }

        [ActionName("CompanyUpdate"), HttpPost]
        public IActionResult CompanyUpdate(string name, string website, string email)
        {         
            string newName = ModelState["Name"].AttemptedValue;
            string newEmail = ModelState["Email"].AttemptedValue;
            string newWebsite = ModelState["Website"].AttemptedValue;

            DatabaseManagement.UpdateACompany(
                newName,
                newWebsite,
                newEmail,
                null
                );
           
            return RedirectToAction("CompanyView");
        }

        public IActionResult Employee()
        {
            ViewBag.Title = "Employee Management";

            return View();
        }

        public IActionResult EmployeeAdd()
        {
            ViewBag.Title = "Add Employee";

            return View();
        }

        [ActionName("EmployeeAdd"), HttpPost]
        public IActionResult EmployeeAdd(string firstName, string lastName, string placeOfWork, string email, string phoneNumber)
        {
            Employee employeeToAdd = new Employee()
            {
                FirstName = ModelState["FirstName"].AttemptedValue,
                LastName = ModelState["LastName"].AttemptedValue,
                PhoneNumber = ModelState["PhoneNumber"].AttemptedValue,
                Email = ModelState["Email"].AttemptedValue
            };

            if (ModelState["PlaceOfWork"].AttemptedValue != "none")
            {
                using(Context context = new Context())
                {
                    employeeToAdd.PlaceOfWork = context.Companies.Find(int.Parse(ModelState["PlaceOfWork"].AttemptedValue));
                }
            }
            
            DatabaseManagement.AddEmployeeToDb(employeeToAdd);
            return RedirectToAction("Employee");
        }

        public IActionResult EmployeeSearch()
        {
            ViewBag.Title = "Search for Employee";
            return View();
        }

        [ActionName("EmployeeSearch"), HttpPost]
        public IActionResult EmployeeSearch(string firstName, string lastName, string placeOfWork, string email, string phoneNumber)
        {
           
            DatabaseManagement.GetRefinedEmployeeSearchResults(
                ModelState["FirstName"].AttemptedValue, 
                ModelState["LastName"].AttemptedValue,  
                ModelState["PlaceOfWork"].AttemptedValue,
                ModelState["PhoneNumber"].AttemptedValue, 
                ModelState["Email"].AttemptedValue
            );

            return RedirectToAction("EmployeeSearchResults");
        }

        public IActionResult EmployeeSearchResults()
        {
            ViewBag.Title = "Employee Search Results";
            return View();
        }

        [ActionName("EmployeeSearchResults"), HttpPost]
        public IActionResult EmployeeSearchResults(Employee employee)
        {
            ViewBag.EmployeeToView = employee;
            return RedirectToAction("EmployeeUpdate");
        }

        public IActionResult EmployeeUpdate()
        {
            ViewBag.Title = "Update Employee";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult EmployeeView()
        {
            ViewBag.Title = "View Employee";
            return View();
        }

        public IActionResult EmployeeDelete()
        {
            ViewBag.Title = "Delete Employee";
            return View();
        }

        public ActionResult DeleteEmployee(string deleteEmployee)
        {
            using (Context context = new Context())
            {
                DatabaseManagement.SelectedEmployee = context.Employees.Find(Int32.Parse(deleteEmployee));
            }
            return RedirectToAction("EmployeeDelete");
        }

        public ActionResult ConfirmDeleteEmployee()
        {
            using (Context context = new Context())
            {
                DatabaseManagement.DeleteEmployeeFromDb(DatabaseManagement.SelectedEmployee);
            }
            return RedirectToAction("Employee");
        }

        public ActionResult SelectEmployee(string updateEmployee)
        {
            using (Context context = new Context())
            {
                foreach(Employee employee in context.Employees)
                {
                    if(employee.Id == Int32.Parse(updateEmployee))
                    {
                        DatabaseManagement.SelectedEmployee = employee;
                        break;
                    }
                }
                if (DatabaseManagement.SelectedEmployee.PlaceOfWork != null)
                {
                    DatabaseManagement.SelectedCompany = DatabaseManagement.SelectedEmployee.PlaceOfWork;
                }
            }
            
            return RedirectToAction("EmployeeView");
        }

        [ActionName("EmployeeUpdate"), HttpPost]
        public IActionResult EmployeeUpdate(string firstName, string lastName, string placeOfWork, string email, string phoneNumber)
        {
            string newFname = ModelState["FirstName"].AttemptedValue;
            string newLname = ModelState["LastName"].AttemptedValue;
            string newPow = ModelState["PlaceOfWork"].AttemptedValue;
            string newNum = ModelState["PhoneNumber"].AttemptedValue;
            string newEmail = ModelState["Email"].AttemptedValue;

            DatabaseManagement.UpdateAnEmployee(
                newFname,
                newLname,
                newPow,
                newEmail,
                newNum
                );

            return RedirectToAction("EmployeeView");
        }
    }
}

Views/DatabaseManager/Company.cshtml
<div class="main-nav-btns row-flex flex-center">
    <a href="/DatabaseManager/CompanySearch" class="btn">Search <i class="fas fa-search"></i></a>
    <a href="/DatabaseManager/CompanyAdd" class="btn">Add Entry <i class="fas fa-plus"></i></a>
</div>

<div class="container">
    <div class="search-results-cntr column-flex">

    @using(Context context = new Context())
    {
        if( context.Companies.Count() == 0) { 
            <div class="text-center">The company database is empty.</div>
        } 
        else
        {
            @foreach (Company company in context.Companies)
            {
                <div class="search-result row-flex flex-between">
                    <div class="result-detail">
                        <p class="detail-element">@company.DisplayName()</p>
                       
                        @if(company.Website != null && company.Website != "")
                        {
                            <p class="detail-element">@company.DisplayWebsite()</p>    
                        }

                        @if(company.Email != null && company.Email != "")
                        {
                            <p class="detail-element">@company.DisplayEmail()</p>
                        }
                    </div>
                    

                    <div class="search-result-btn-cntr">
                        @using(Html.BeginForm("SelectCompany", "DatabaseManager"))
                        {
                            <button class="btn" name="updateCompany" type="submit" value="@company.Id"><i class="fas fa-folder-open"></i></button>
                        }

                        @using(Html.BeginForm("DeleteCompany", "DatabaseManager"))
                        {
                            <button class="btn" name="deleteCompany" type="submit" value="@company.Id"><i class="fas fa-trash"></i></button>
                        }
                    </div>
                </div>
            }
        }
    }
    </div>
</div>

Views/DatabaseManager/CompanyAdd.cshtml
<div id="company-add" class="container">
    <h3 class="text-center">Add a @ViewBag.DatabaseType to the Database</h3>

    <form class="column-flex form" method="post">
        <label for="companyNameAdd">@ViewBag.DatabaseType Name:</label>
        <input id="companyNameAdd" name="name" required>

        <label for="companyEmailInput">@ViewBag.DatabaseType Email Address:</label>
        <input  id="companyEmailInput" name="email">

        <label for="companyWebsiteInput">@ViewBag.DatabaseType Website:</label>
        <input id="companyWebsiteInput" name="website">

        <button type="submit" id="companySubmitBtn" class="btn">Add <i class="fas fa-check"></i></button>
    
        <p id="companyErrorMessage"></p>
    </form>
</div>

<script src="~/js/companyValidation.js" asp-append-version="true"></script>

Views/DatabaseManager/CompanyDelete.cshtml
<div id="company-update" class="container">
    <h3 class="text-center">Update a @ViewBag.DatabaseType</h3>

    <div class="form update row-flex" method="post">
        <div class="flex-cntr">
            <div class="column-flex">
                <label>Company Name:</label>
                <p>@DatabaseManagement.SelectedCompany.Name</p>

            </div>
        </div>
            
        <div class="flex-cntr">
            <div class="column-flex">
                <label>Company Email Address:</label>
                <p>@DatabaseManagement.SelectedCompany.Email</p>
            </div>
        </div>

        <div class="flex-cntr">
            <div class="column-flex">
                <label>Company Website:</label>
                <p>@DatabaseManagement.SelectedCompany.Website</p>
            </div>
        </div>

        @using(Html.BeginForm("ConfirmDeleteCompany", "DatabaseManager"))
        {
            <button class="btn" name="deleteCompany" type="submit" value="@DatabaseManagement.SelectedCompany.Id"> Confirm Delete <i class="fas fa-trash"></i></button>
        }
    </div>
</div>

Views/DatabaseManager/CompanySearchResults.cshtml
<div id="company-search-results" class="container">
        
    <h3>Search Results:</h3>
    <div class="search-results-cntr column-flex">

       @if( DatabaseManagement.CompanySearchResults[3].Count() == 0) { 
            <div class="text-center">No entries matched your search terms.</div>
        } 
        else
        {
            
            @foreach (Company company in DatabaseManagement.CompanySearchResults[3])
            {
                <div class="search-result row-flex flex-between">
                    <div class="result-detail">
                        <p class="detail-element">@company.DisplayName()</p>
                       
                        @if(company.Website != null && company.Website != "")
                        {
                            <p class="detail-element">@company.DisplayWebsite()</p>    
                        }

                        @if(company.Email != null && company.Email != "")
                        {
                            <p class="detail-element">@company.DisplayEmail()</p>
                        }
                    </div>
                    
                    <div class="search-result-btn-cntr">
                        @using(Html.BeginForm("ViewCompany", "DatabaseManager"))
                        {
                            <button class="btn" name="updateCompany" type="submit" value="@company.Id"><i class="fas fa-folder-open"></button>
                        }

                        @using(Html.BeginForm("DeleteCompany", "DatabaseManager"))
                        {
                            <button class="btn" name="deleteCompany" type="submit" value="@company.Id"><i class="fas fa-trash"></button>
                        }
                    </div>
                </div>
            }
        }
    </div>

    <div class="delete-warning-message">
        <p>Are you sure you want to delete "###" from the "###" Database?</p>
        <div class="row-flex flex-center">
            <button class="btn">Yes</button>
            <button class="btn">No</button>
        </div>
    </div>

</div>

Views/DatabaseManager/CompanyUpdate.cshtml
<div id="company-update" class="container">
    <h3 class="text-center">Update Company</h3>

    <form class="form update row-flex" method="post">
        <div class="flex-cntr">
            <div class="column-flex">
                <label for="companyNameAdd">New @ViewBag.DatabaseType Name:</label>
                <input id="companyNameAdd" name="Name" value="@DatabaseManagement.SelectedCompany.Name">
            </div>
        </div>
            
        <div class="flex-cntr">
            <div class="column-flex">
                <label for="companyEmailInput">New @ViewBag.DatabaseType Email Address:</label>
                <input id="companyEmailInput" name="Email" value="@DatabaseManagement.SelectedCompany.Email">
            </div>
                    
        </div>

        <div class="flex-cntr">
            <div class="column-flex">
                <label for="companyWebsiteInput">New @ViewBag.DatabaseType Website:</label>
                <input id="companyWebsiteInput" name="Website" value="@DatabaseManagement.SelectedCompany.Website">
            </div>
        </div>
                
        <button type="submit" id="companySubmitBtn" class="btn">Update <i class="fas fa-check"></i></button>
         
        <p id="companyErrorMessage"></p>
    </form>
</div>

<script src="~/js/companyValidation.js" asp-append-version="true"></script>

Views/DatabaseManager/CompanyView.cshtml
<div id="company-update" class="container">
    <h3 class="text-center">Viewing Company</h3>

    <div class="view row-flex" method="post">
        <div class="flex-cntr row-flex">
            <div class="column-flex">
                <label>Company Name:</label>
                <p>@DatabaseManagement.SelectedCompany.Name</p>
            </div>
            <div class="column-flex">
                <label>Company Email Address:</label>
                @if(@DatabaseManagement.SelectedCompany.Email != "")
                {
                    <p>@DatabaseManagement.SelectedCompany.Email</p>
                } 
                else
                {
                    <p>None on record.</p>
                }
            </div>
        </div>

        <div class="flex-cntr">
            <div class="column-flex">
                <label>Company Website:</label>
                @if(@DatabaseManagement.SelectedCompany.Website != "")
                {
                    <p>@DatabaseManagement.SelectedCompany.Website</p>
                } 
                else
                {
                    <p>None on record.</p>
                }
            </div>
        </div>
        <div class="viewBtns row-flex">
            <a class="btn" name="updateCompany" href="/DatabaseManager/CompanyUpdate"><i class="fas fa-pen"></i></a>

            @using(Html.BeginForm("DeleteCompany", "DatabaseManager"))
            {
                <button class="btn" name="deleteCompany" type="submit" value="@DatabaseManagement.SelectedCompany.Id"><i class="fas fa-trash"></i></button>
            }
        </div>
        
    </div>
</div>

Views/DatabaseManager/Employee.cshtml
<div class="main-nav-btns row-flex flex-center">
    <a href="/DatabaseManager/EmployeeSearch" class="btn">Search <i class="fas fa-search"></i></a>
    <a href="/DatabaseManager/EmployeeAdd" class="btn">Add Entry <i class="fas fa-plus"></i></a>
</div>

<div class="container">
    <div class="search-results-cntr column-flex">

    @using(Context context = new Context())
    {
        if( context.Employees.Count() == 0) { 
            <div class="text-center">The employee database is empty.</div>
        } 
        else
        {
            @foreach (Employee employee in context.Employees)
            {
                <div class="search-result row-flex flex-between">
                    <div class="result-detail">
                        <p class="detail-element">@employee.DisplayName()</p>
                       
                        @if(employee.PlaceOfWork != null)
                        {
                            <p class="detail-element">@employee.DisplayCompany()</p>    
                        }

                        @if(employee.PhoneNumber != null && employee.PhoneNumber != "")
                        {
                            <p class="detail-element">@employee.DisplayNumber()</p>
                        }

                        @if(employee.Email != null && employee.Email != "")
                        {
                            <p class="detail-element">@employee.DisplayEmail()</p>
                        }
                    </div>
                    
                    <div class="search-result-btn-cntr">
                        @using(Html.BeginForm("SelectEmployee", "DatabaseManager"))
                        {
                            <button class="btn" name="updateEmployee" type="submit" value="@employee.Id"><i class="fas fa-folder-open"></i></button>
                        }

                        @using(Html.BeginForm("DeleteEmployee", "DatabaseManager"))
                        {
                            <button class="btn" name="deleteEmployee" type="submit" value="@employee.Id"><i class="fas fa-trash"></i></button>
                        }
                    </div>
                </div>
            }
        }
    }
    </div>
</div>

Views/DatabaseManager/EmployeeAdd.cshtml
<div id="employee-add" class="container">
    <h3 class="text-center">Add an @ViewBag.DatabaseType to the Database</h3>
    <form class="column-flex form" method="post">
            
        <label for="fNameInput">First Name:</label>
        <input id="fNameInput" name="FirstName" required>

        <label for="lNameInput">Last Name:</label>
        <input id="lNameInput" name="LastName" required>

        <label for="emailInput">Email Address:</label>
        <input  id="emailInput"  name="Email">

        <label  for="poWInput">Place of Work:</label>
        
        @using(Context context = new Context())
        {
            if(context.Companies.Count() == 0)
            {
                 <p>No companies are currently stored in the database.</p>
            }
            else
            {
                <select id="poWInput"  name="PlaceOfWork">
                    <option value="none">N/A</option>
                    @foreach(Company company in context.Companies)
                    {
                    <option value="@company.Id">@company.Name</option>
                    }
                </select>
            }
        }

        <label for="numInput">Phone Number:</label>
        <input id="numInput" name="PhoneNumber">

        <button type="submit" id="employeeSubmitBtn" class="btn">Add</button>

        <p id="employeeErrorMessage"></p>
    </form>
</div>

<script src="~/js/employeeValidation.js" asp-append-version="true"></script>

Views/DatabaseManager/EmployeeDelete.cshtml
@using DatabaseManager

<div id="employee-update" class="container">
    <h3 class="text-center">Update an @ViewBag.DatabaseType</h3>
    <div class="update column-flex" method="post">
        <div class="flex-cntr">
            <div class="column-flex">
                <label>First Name:</label>
                <p>@DatabaseManagement.SelectedEmployee.FirstName</p>>
            </div>
        </div>

        <div class="flex-cntr">
            <div class="column-flex">
                <label>Last Name:</label>
                <p>@DatabaseManagement.SelectedEmployee.LastName</p>
            </div>
        </div>
            
        <div class="flex-cntr">
            <div class="column-flex">
                <label for="emailInput">Email Address:</label>
                <p>@DatabaseManagement.SelectedEmployee.Email</p>
            </div>         
        </div>

       <div class="flex-cntr">
            <div class="column-flex">
                <label>Place of Work:</label>
                @if (DatabaseManagement.SelectedEmployee.PlaceOfWork != null)
                {
                    <p>@DatabaseManagement.SelectedEmployee.PlaceOfWork.Name</p>
                }
                else
                {
                    <p>Unkown</p>
                }
            </div>            
        </div>
                
        <div class="flex-cntr">
            <div class="column-flex file-input">
                <label>Phone Number:</label>
                <p>@DatabaseManagement.SelectedEmployee.PhoneNumber</p> 
            </div>
        </div>

        @using(Html.BeginForm("ConfirmDeleteEmployee", "DatabaseManager"))
        {
            <button class="btn" name="deleteEmployee" type="submit" value="@DatabaseManagement.SelectedEmployee.Id">Confirm Delete <i class="fas fa-trash"></i></button>
        }
    </div>
</div>

Views/DatabaseManager/EmployeeSearchResults.cshtml
<div id="employee-search-results" class="container">
        
    <h3 >Search Results:</h3>
    <div class="search-results-cntr column-flex">
        
        @if( DatabaseManagement.EmployeeSearchResults[5].Count() == 0) { 
            <div class="text-center">No entries matched your search terms.</div>
        } 
        else
        {
            @foreach (Employee employee in DatabaseManagement.EmployeeSearchResults[5])
            {
                <div class="search-result row-flex flex-between">
                    <div class="result-detail">
                        <p class="detail-element">@employee.DisplayName()</p>
                       
                        @if(employee.PlaceOfWork != null)
                        {
                            <p class="detail-element">@employee.DisplayCompany()</p>    
                        }

                        @if(employee.PhoneNumber != null && employee.PhoneNumber != "")
                        {
                            <p class="detail-element">@employee.DisplayNumber()</p>
                        }

                        @if(employee.Email != null && employee.Email != "")
                        {
                            <p class="detail-element">@employee.DisplayEmail()</p>
                        }
                    </div>
                    
                    <div class="search-result-btn-cntr">
                        @using(Html.BeginForm("ViewEmployee", "DatabaseManager"))
                        {
                            <button class="btn" name="updateEmployee" type="submit" value="@employee.Id"><i class="fas fa-folder-open"></button>
                        }
                        
                        @using(Html.BeginForm("DeleteEmployee", "DatabaseManager"))
                        {
                            <button class="btn" name="deleteEmployee" type="submit" value="@employee.Id"><i class="fas fa-trash"></button>
                        }
                    </div>
                </div>
            }
        }
    </div>

    <div class="delete-warning-message">
        <p>Are you sure you want to delete "###" from the "###" Database?</p>
        <div class="row-flex flex-center">
            <button class="btn">Yes</button>
            <button class="btn">No</button>
        </div>
    </div>

</div>

Views/DatabaseManager/EmployeeView.cshtml
@using DatabaseManager

<div id="employee-update" class="container">
    <h3 class="text-center">Viewing Employee</h3>
    <div class="view column-flex" method="post">
        <div class="flex-cntr row-flex">
            <div class="column-flex">
                <label>First Name:</label>
                <p>@DatabaseManagement.SelectedEmployee.FirstName</p>
            </div>
            <div class="column-flex">
                <label>Last Name:</label>
                <p>@DatabaseManagement.SelectedEmployee.LastName</p>
            </div>
        </div>
            
        <div class="flex-cntr row-flex">
            <div class="column-flex">
                <label for="emailInput">Email Address:</label>
                @if(@DatabaseManagement.SelectedEmployee.Email != "")
                {
                    <p>@DatabaseManagement.SelectedEmployee.Email</p>
                } 
                else
                {
                    <p>None on record.</p>
                }
            </div>     
            <div class="column-flex">
                <label>Place of Work:</label>
                @if (DatabaseManagement.SelectedEmployee.PlaceOfWork != null)
                {
                    <p>@DatabaseManagement.SelectedEmployee.PlaceOfWork.Name</p>
                }
                else
                {
                    <p>None on record.</p>
                }
            </div>  
        </div>
                
        <div class="flex-cntr">
            <div class="column-flex">
                <label>Phone Number:</label>
                @if(@DatabaseManagement.SelectedEmployee.PhoneNumber != "")
                {
                    <p>@DatabaseManagement.SelectedEmployee.PhoneNumber</p>
                } 
                else
                {
                    <p>None on record.</p>
                }
            </div>
        </div>
        
        <div class="row-flex viewBtns">
             <a class="btn" name="updateEmployee" href="/DatabaseManager/EmployeeUpdate"><i class="fas fa-pen"></i></a>

            @using(Html.BeginForm("DeleteEmployee", "DatabaseManager"))
            {
                <button class="btn" name="deleteEmployee" type="submit" value="@DatabaseManagement.SelectedEmployee.Id"><i class="fas fa-trash"></i></button>
            }
        </div>
       
    </div>
</div>

Views/DatabaseManager/Index.cshtml
<div class="main-nav-btns flex-center">
    <a class="btn" href="/DatabaseManager/Company">Companies</a>
    <a class="btn" href="/DatabaseManager/Employee">Employees</a>
</div>